# Generated by Django 2.2.2 on 2021-03-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(default='', max_length=50, null=True)),
                ('class_subject', models.CharField(default='', max_length=50, null=True)),
                ('class_date', models.CharField(default='', max_length=50, null=True)),
                ('class_time', models.CharField(default='', max_length=50, null=True)),
                ('number_of_students', models.CharField(default='', max_length=50, null=True)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=50, null=True)),
                ('role_status', models.CharField(default='', max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('usercode', models.CharField(default='', max_length=50, null=True)),
                ('student_name', models.CharField(default='', max_length=50, null=True)),
                ('student_email', models.CharField(default='', max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('usercode', models.CharField(default='', max_length=50, null=True)),
                ('teacher_name', models.CharField(default='', max_length=50, null=True)),
                ('teacher_email', models.CharField(default='', max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(default='', max_length=50, null=True)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('useremail', models.CharField(default='', max_length=100, null=True)),
                ('password', models.CharField(default='', max_length=100, null=True)),
                ('status', models.CharField(default='active', max_length=50, null=True)),
                ('user_created_time', models.DateTimeField(auto_now_add=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_app.Role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ClassStudentMapping',
            fields=[
                ('cls_student_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_app.Classes')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_app.Student')),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_app.Teacher'),
        ),
    ]
