# Generated by Django 2.2.2 on 2021-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='number_of_students',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
