# Generated by Django 2.2.2 on 2021-04-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0003_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='signature',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
