# Generated by Django 2.2.2 on 2021-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0004_auto_20210403_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='google_token_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
